# Generated by Django 4.2.4 on 2023-10-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("about", models.CharField(max_length=500)),
                ("pages", models.IntegerField(max_length=400)),
            ],
        ),
    ]
